#!/usr/bin/env python
# -*- coding: utf-8 -*-

from Colors import Colors

class PaletteTypes(object):
  
  # the palette names are just indexes into a table
  blackWhite = 0
  whiteBlack = 1

  paletteTable = [
    # note that the order doesn't matter
    [Colors.pink, Colors.pink],
    [Colors.pink, Colors.yellow],
    [Colors.pink, Colors.green],
    [Colors.pink, Colors.orange],
    [Colors.pink, Colors.violet],
    [Colors.pink, Colors.rubyRed],
    [Colors.pink, Colors.deepTurquoise],
    [Colors.pink, Colors.white],
    [Colors.pink, Colors.black],
    [Colors.yellow, Colors.pink],
    [Colors.yellow, Colors.yellow],
    [Colors.yellow, Colors.green],
    [Colors.yellow, Colors.orange],
    [Colors.yellow, Colors.violet],
    [Colors.yellow, Colors.rubyRed],
    [Colors.yellow, Colors.deepTurquoise],
    [Colors.yellow, Colors.white],
    [Colors.yellow, Colors.black],
    [Colors.green, Colors.pink],
    [Colors.green, Colors.yellow],
    [Colors.green, Colors.green],
    [Colors.green, Colors.orange],
    [Colors.green, Colors.violet],
    [Colors.green, Colors.rubyRed],
    #[Colors.green, Colors.deepTurquoise],
    [Colors.green, Colors.white],
    [Colors.green, Colors.black],
    [Colors.orange, Colors.pink],
    [Colors.orange, Colors.yellow],
    [Colors.orange, Colors.green],
    [Colors.orange, Colors.orange],
    [Colors.orange, Colors.violet],
    [Colors.orange, Colors.rubyRed],
    [Colors.orange, Colors.deepTurquoise],
    [Colors.orange, Colors.white],
    [Colors.orange, Colors.black],
    [Colors.violet, Colors.pink],
    [Colors.violet, Colors.yellow],
    [Colors.violet, Colors.green],
    [Colors.violet, Colors.orange],
    [Colors.violet, Colors.violet],
    [Colors.violet, Colors.rubyRed],
    [Colors.violet, Colors.deepTurquoise],
    [Colors.violet, Colors.white],
    [Colors.violet, Colors.black],
    [Colors.rubyRed, Colors.pink],
    [Colors.rubyRed, Colors.yellow],
    [Colors.rubyRed, Colors.green],
    [Colors.rubyRed, Colors.orange],
    [Colors.rubyRed, Colors.violet],
    [Colors.rubyRed, Colors.rubyRed],
    [Colors.rubyRed, Colors.deepTurquoise],
    [Colors.rubyRed, Colors.white],
    [Colors.rubyRed, Colors.black],
    [Colors.deepTurquoise, Colors.pink],
    [Colors.deepTurquoise, Colors.yellow],
    #[Colors.deepTurquoise, Colors.green],
    [Colors.deepTurquoise, Colors.orange],
    [Colors.deepTurquoise, Colors.violet],
    [Colors.deepTurquoise, Colors.rubyRed],
    [Colors.deepTurquoise, Colors.deepTurquoise],
    [Colors.deepTurquoise, Colors.white],
    [Colors.deepTurquoise, Colors.black],
    [Colors.white, Colors.pink],
    [Colors.white, Colors.yellow],
    [Colors.white, Colors.green],
    [Colors.white, Colors.orange],
    [Colors.white, Colors.violet],
    [Colors.white, Colors.rubyRed],
    [Colors.white, Colors.deepTurquoise],
    [Colors.white, Colors.white],
    [Colors.white, Colors.black],
    [Colors.black, Colors.pink],
    [Colors.black, Colors.yellow],
    [Colors.black, Colors.green],
    [Colors.black, Colors.orange],
    [Colors.black, Colors.violet],
    [Colors.black, Colors.rubyRed],
    [Colors.black, Colors.deepTurquoise],
    [Colors.black, Colors.white],
    [Colors.black, Colors.black],
  ]
  
